version: '3.7'
services:
  app:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    ports:
      - "8190:8190"
    volumes:
      - app_data:/app/data

  db:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  app_data:
  db_data: