version: '3.7'
services:
  mongodb-conteiner:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: cloudPassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_conteiner: /data/db

volumes:
  mongodb_data_conteiner: